version: "3.8"

services:
  postgres:
    container_name: fast-api-first
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fast
      POSTGRES_DB: fast-db