@baseURL = http://localhost:8000
@accessToken = {{authenticate.response.body.access_token}}
GET {{baseURL}}/questions/4

###

POST {{baseURL}}/questions
Content-Type: application/json

{
  "questionText": "O que React?",
  "choices": [
    {"choiceText": "Framework", "isCorrect": true},
    {"choiceText": "Ambiente", "isCorrect": false},
    {"choiceText": "Banco de dados", "isCorrect": false}
  ]
}

###
POST {{baseURL}}/users
Content-Type: application/json

{
  "name": "lucas",
  "email": "lucas2@gmail.com",
  "password": "password123"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
  "email": "lucas2@gmail.com",
  "password": "password123"
}

###

GET {{baseURL}}/profile
Authorization: Bearer {{accessToken}}